### PR TITLE
Various optimizations

### PR DESCRIPTION
**Pull request by billw2012**
- removing a slow critical section from our totally single threaded code
[*] academy required literature now and can't be force built
- removed ForceBuild completely
- unit class Buildings is now a vector of ids instead of mask of bools

### CODE REVIEW

**Comment by ghost** [comment]
What makes you think C2C is only singlethreaded?
The property System is running on 4 threads and the multithreading of the city turn processing can be activated by changing a single number in a xml file.
You can't remove any critical section before the multithreaded code is removed.

**Comment by billw2012** [comment]
Being specifically told that it was single threaded made me think it was. I will put the critical section back, it is a real shame though, that one is kill perf badly, and removing it so far showed zero problems. I know that isn't enough in a multithreaded context to consider a change like this okay, I was relying on what other people told me.

**Comment by ghost** [comment]
I try to get the removal of the multithreaded code including all critical sections done in the next 2 weeks.

**Review by Thunderbrd — APPROVED** [review]
I'd be crazy to review ALL of this but it looks straight, what I did take a look at.

**Pull request merged**
